#include <assert.h>
#include <stdio.h>
#include <stdlib.h>   /* mkstemp */
#include <string.h>
#include "symbols.h"

/* Write `text` to a temp file and load it; returns the table or NULL. */
static symbols_t *load_str(const char *text)
{
    char path[] = "/tmp/boyless_sym_XXXXXX";
    int fd = mkstemp(path);
    assert(fd >= 0);
    FILE *f = fdopen(fd, "w");
    assert(f);
    fputs(text, f);
    fclose(f);
    symbols_t *s = NULL;
    bool ok = symbols_load(path, &s);
    remove(path);
    return ok ? s : NULL;
}

static void test_load_and_lookup(void)
{
    symbols_t *s = load_str(
        "; File generated by rgblink\n"
        "00:0000 Start\n"
        "00:0004 Start.waitvb\n"
        "00:c000 wValue\n"
        "\n"
        "01:4000 BankedThing\n");
    assert(s);
    uint16_t a = 0;
    assert(symbols_lookup(s, "Start", &a) && a == 0x0000);
    assert(symbols_lookup(s, "Start.waitvb", &a) && a == 0x0004);
    assert(symbols_lookup(s, "wValue", &a) && a == 0xC000);
    assert(symbols_lookup(s, "BankedThing", &a) && a == 0x4000); /* bank dropped */
    assert(!symbols_lookup(s, "wvalue", &a));   /* case-sensitive */
    assert(!symbols_lookup(s, "Missing", &a));
    assert(!symbols_lookup(NULL, "Start", &a));
    symbols_free(s);
}

static void test_first_wins(void)
{
    symbols_t *s = load_str("00:c000 dup\n00:d000 dup\n");
    assert(s);
    uint16_t a = 0;
    assert(symbols_lookup(s, "dup", &a) && a == 0xC000); /* first occurrence */
    symbols_free(s);
}

static void test_malformed_line_fails(void)
{
    assert(load_str("00:c000 wValue\nnonsense_without_colon_or_label\n") == NULL);
}

int main(void)
{
    test_load_and_lookup();
    test_first_wins();
    test_malformed_line_fails();
    printf("test_symbols: OK\n");
    return 0;
}
